// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLJ3Eb9dDOiS_KlsMy5o7i5MBFmwKgXAI',
    appId: '1:465792105360:android:f3f7479144e26a68105115',
    messagingSenderId: '465792105360',
    projectId: 'appexchangethings',
    storageBucket: 'appexchangethings.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg78dlz6gazf7w2ziSbx8-gxOuOnWCiYM',
    appId: '1:465792105360:ios:c5cbbc95f0fcc515105115',
    messagingSenderId: '465792105360',
    projectId: 'appexchangethings',
    storageBucket: 'appexchangethings.appspot.com',
    androidClientId: '465792105360-sgsjegdprilup8057r6q4dv3u6t8i27n.apps.googleusercontent.com',
    iosClientId: '465792105360-ss7nr2qett72qjjmi05i3s7e90ah0pld.apps.googleusercontent.com',
    iosBundleId: 'com.example.exchange',
  );
}
